name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código-fonte
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configurar o JDK 8
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      # Executar o script libs.sh para instalar dependências externas
      - name: Install external dependencies
        run: |
          chmod +x ./libs.sh
          ./libs.sh

      # Construir o projeto com Maven
      - name: Build with Maven
        run: mvn clean verify --file pom.xml

      # Gerar o badge de cobertura de testes com JaCoCo
      - name: Generate JaCoCo Coverage Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-path: target/site/jacoco/jacoco.csv
          badge-output-path: coverage/badge.svg

      # Fazer upload do relatório JaCoCo como artefato
      - name: Upload JaCoCo Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v1
