name: Java CI with Maven

# Define quando o pipeline será executado
on:
  push:
    branches: [ master ]  # Roda quando há push na branch 'main'
  pull_request:
    branches: [ master ]  # Roda quando há pull request para a branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Define o ambiente de execução

    steps:
    # 1. Checkout do código no repositório
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. Configurar o JDK (Java)
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    # 3. Compilar o projeto com Maven
    - name: Build with Maven
      run: mvn clean install

    # 4. Executar os testes
    - name: Run tests
      run: mvn test

    # 5. Gerar cobertura de código (com JaCoCo, se configurado no pom.xml)
    - name: Generate coverage report
      run: mvn verify

    # 6. Salvar o relatório de cobertura como artefato
    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: target/site/jacoco/index.html
