name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout do repositório
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Configurar o JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    # 3. Compilar o projeto com Maven
    - name: Build with Maven
      run: mvn clean install

    # 4. Executar os testes
    - name: Run tests
      run: mvn test

    # 5. Gerar cobertura de código (com JaCoCo, se configurado no pom.xml)
    - name: Generate coverage report
      run: mvn verify

    # 6. Salvar o relatório de cobertura como artefato
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: target/site/jacoco/index.html
